// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eve_launcher/application.proto

#include "eve_launcher/application.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_eve_5flauncher_2fapplication_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_eve_5flauncher_2fapplication_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Application;
}  // namespace protobuf_eve_5flauncher_2fapplication_2eproto
namespace eve_launcher {
namespace application {
class EventMetadataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<EventMetadata>
      _instance;
} _EventMetadata_default_instance_;
class ApplicationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Application>
      _instance;
  bool no_installer_provider_;
  ::google::protobuf::internal::ArenaStringPtr installer_provider_;
} _Application_default_instance_;
}  // namespace application
}  // namespace eve_launcher
namespace protobuf_eve_5flauncher_2fapplication_2eproto {
static void InitDefaultsEventMetadata() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::eve_launcher::application::_EventMetadata_default_instance_;
    new (ptr) ::eve_launcher::application::EventMetadata();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::eve_launcher::application::EventMetadata::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_EventMetadata =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsEventMetadata}, {
      &protobuf_eve_5flauncher_2fapplication_2eproto::scc_info_Application.base,}};

static void InitDefaultsApplication() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::eve_launcher::application::_Application_default_instance_;
    new (ptr) ::eve_launcher::application::Application();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::eve_launcher::application::Application::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Application =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsApplication}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_EventMetadata.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Application.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::eve_launcher::application::EventMetadata, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::eve_launcher::application::EventMetadata, md5_session_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::eve_launcher::application::EventMetadata, application_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::eve_launcher::application::EventMetadata, operating_system_uuid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::eve_launcher::application::Application, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::eve_launcher::application::Application, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::eve_launcher::application::Application, version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::eve_launcher::application::Application, build_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::eve_launcher::application::Application, region_),
  offsetof(::eve_launcher::application::ApplicationDefaultTypeInternal, no_installer_provider_),
  offsetof(::eve_launcher::application::ApplicationDefaultTypeInternal, installer_provider_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::eve_launcher::application::Application, provider_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::eve_launcher::application::EventMetadata)},
  { 8, -1, sizeof(::eve_launcher::application::Application)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::eve_launcher::application::_EventMetadata_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::eve_launcher::application::_Application_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "eve_launcher/application.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\036eve_launcher/application.proto\022\030eve_la"
      "uncher.application\"\177\n\rEventMetadata\022\023\n\013m"
      "d5_session\030\001 \001(\014\022:\n\013application\030\002 \001(\0132%."
      "eve_launcher.application.Application\022\035\n\025"
      "operating_system_uuid\030\003 \001(\014\"\230\003\n\013Applicat"
      "ion\022\017\n\007version\030\001 \001(\t\022C\n\nbuild_type\030\002 \001(\016"
      "2/.eve_launcher.application.Application."
      "BuildType\022<\n\006region\030\003 \001(\0162,.eve_launcher"
      ".application.Application.Region\022\037\n\025no_in"
      "staller_provider\030\004 \001(\010H\000\022\034\n\022installer_pr"
      "ovider\030\005 \001(\tH\000\"d\n\tBuildType\022\031\n\025BUILDTYPE"
      "_UNSPECIFIED\020\000\022\025\n\021BUILDTYPE_RELEASE\020\001\022\022\n"
      "\016BUILDTYPE_BETA\020\002\022\021\n\rBUILDTYPE_DEV\020\003\"D\n\006"
      "Region\022\026\n\022REGION_UNSPECIFIED\020\000\022\020\n\014REGION"
      "_WORLD\020\001\022\020\n\014REGION_CHINA\020\002B\n\n\010providerBW"
      "ZCgithub.com/ccpgames/eve-proto-go/gener"
      "ated/eve_launcher/application\252\002\017EveLaunc"
      "her.Appb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 695);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "eve_launcher/application.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_eve_5flauncher_2fapplication_2eproto
namespace eve_launcher {
namespace application {
const ::google::protobuf::EnumDescriptor* Application_BuildType_descriptor() {
  protobuf_eve_5flauncher_2fapplication_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_eve_5flauncher_2fapplication_2eproto::file_level_enum_descriptors[0];
}
bool Application_BuildType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Application_BuildType Application::BUILDTYPE_UNSPECIFIED;
const Application_BuildType Application::BUILDTYPE_RELEASE;
const Application_BuildType Application::BUILDTYPE_BETA;
const Application_BuildType Application::BUILDTYPE_DEV;
const Application_BuildType Application::BuildType_MIN;
const Application_BuildType Application::BuildType_MAX;
const int Application::BuildType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* Application_Region_descriptor() {
  protobuf_eve_5flauncher_2fapplication_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_eve_5flauncher_2fapplication_2eproto::file_level_enum_descriptors[1];
}
bool Application_Region_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Application_Region Application::REGION_UNSPECIFIED;
const Application_Region Application::REGION_WORLD;
const Application_Region Application::REGION_CHINA;
const Application_Region Application::Region_MIN;
const Application_Region Application::Region_MAX;
const int Application::Region_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void EventMetadata::InitAsDefaultInstance() {
  ::eve_launcher::application::_EventMetadata_default_instance_._instance.get_mutable()->application_ = const_cast< ::eve_launcher::application::Application*>(
      ::eve_launcher::application::Application::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EventMetadata::kMd5SessionFieldNumber;
const int EventMetadata::kApplicationFieldNumber;
const int EventMetadata::kOperatingSystemUuidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EventMetadata::EventMetadata()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_eve_5flauncher_2fapplication_2eproto::scc_info_EventMetadata.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:eve_launcher.application.EventMetadata)
}
EventMetadata::EventMetadata(const EventMetadata& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  md5_session_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.md5_session().size() > 0) {
    md5_session_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.md5_session_);
  }
  operating_system_uuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.operating_system_uuid().size() > 0) {
    operating_system_uuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operating_system_uuid_);
  }
  if (from.has_application()) {
    application_ = new ::eve_launcher::application::Application(*from.application_);
  } else {
    application_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:eve_launcher.application.EventMetadata)
}

void EventMetadata::SharedCtor() {
  md5_session_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operating_system_uuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  application_ = NULL;
}

EventMetadata::~EventMetadata() {
  // @@protoc_insertion_point(destructor:eve_launcher.application.EventMetadata)
  SharedDtor();
}

void EventMetadata::SharedDtor() {
  md5_session_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operating_system_uuid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete application_;
}

void EventMetadata::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* EventMetadata::descriptor() {
  ::protobuf_eve_5flauncher_2fapplication_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_eve_5flauncher_2fapplication_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EventMetadata& EventMetadata::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_eve_5flauncher_2fapplication_2eproto::scc_info_EventMetadata.base);
  return *internal_default_instance();
}


void EventMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:eve_launcher.application.EventMetadata)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  md5_session_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operating_system_uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && application_ != NULL) {
    delete application_;
  }
  application_ = NULL;
  _internal_metadata_.Clear();
}

bool EventMetadata::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:eve_launcher.application.EventMetadata)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes md5_session = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_md5_session()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .eve_launcher.application.Application application = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_application()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes operating_system_uuid = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_operating_system_uuid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:eve_launcher.application.EventMetadata)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:eve_launcher.application.EventMetadata)
  return false;
#undef DO_
}

void EventMetadata::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:eve_launcher.application.EventMetadata)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes md5_session = 1;
  if (this->md5_session().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->md5_session(), output);
  }

  // .eve_launcher.application.Application application = 2;
  if (this->has_application()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_application(), output);
  }

  // bytes operating_system_uuid = 3;
  if (this->operating_system_uuid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->operating_system_uuid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:eve_launcher.application.EventMetadata)
}

::google::protobuf::uint8* EventMetadata::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:eve_launcher.application.EventMetadata)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes md5_session = 1;
  if (this->md5_session().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->md5_session(), target);
  }

  // .eve_launcher.application.Application application = 2;
  if (this->has_application()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_application(), deterministic, target);
  }

  // bytes operating_system_uuid = 3;
  if (this->operating_system_uuid().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->operating_system_uuid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:eve_launcher.application.EventMetadata)
  return target;
}

size_t EventMetadata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:eve_launcher.application.EventMetadata)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes md5_session = 1;
  if (this->md5_session().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->md5_session());
  }

  // bytes operating_system_uuid = 3;
  if (this->operating_system_uuid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->operating_system_uuid());
  }

  // .eve_launcher.application.Application application = 2;
  if (this->has_application()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *application_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EventMetadata::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:eve_launcher.application.EventMetadata)
  GOOGLE_DCHECK_NE(&from, this);
  const EventMetadata* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EventMetadata>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:eve_launcher.application.EventMetadata)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:eve_launcher.application.EventMetadata)
    MergeFrom(*source);
  }
}

void EventMetadata::MergeFrom(const EventMetadata& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:eve_launcher.application.EventMetadata)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.md5_session().size() > 0) {

    md5_session_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.md5_session_);
  }
  if (from.operating_system_uuid().size() > 0) {

    operating_system_uuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operating_system_uuid_);
  }
  if (from.has_application()) {
    mutable_application()->::eve_launcher::application::Application::MergeFrom(from.application());
  }
}

void EventMetadata::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:eve_launcher.application.EventMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EventMetadata::CopyFrom(const EventMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:eve_launcher.application.EventMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EventMetadata::IsInitialized() const {
  return true;
}

void EventMetadata::Swap(EventMetadata* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EventMetadata::InternalSwap(EventMetadata* other) {
  using std::swap;
  md5_session_.Swap(&other->md5_session_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  operating_system_uuid_.Swap(&other->operating_system_uuid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(application_, other->application_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata EventMetadata::GetMetadata() const {
  protobuf_eve_5flauncher_2fapplication_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_eve_5flauncher_2fapplication_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Application::InitAsDefaultInstance() {
  ::eve_launcher::application::_Application_default_instance_.no_installer_provider_ = false;
  ::eve_launcher::application::_Application_default_instance_.installer_provider_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Application::kVersionFieldNumber;
const int Application::kBuildTypeFieldNumber;
const int Application::kRegionFieldNumber;
const int Application::kNoInstallerProviderFieldNumber;
const int Application::kInstallerProviderFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Application::Application()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_eve_5flauncher_2fapplication_2eproto::scc_info_Application.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:eve_launcher.application.Application)
}
Application::Application(const Application& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.version().size() > 0) {
    version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  ::memcpy(&build_type_, &from.build_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&region_) -
    reinterpret_cast<char*>(&build_type_)) + sizeof(region_));
  clear_has_provider();
  switch (from.provider_case()) {
    case kNoInstallerProvider: {
      set_no_installer_provider(from.no_installer_provider());
      break;
    }
    case kInstallerProvider: {
      set_installer_provider(from.installer_provider());
      break;
    }
    case PROVIDER_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:eve_launcher.application.Application)
}

void Application::SharedCtor() {
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&build_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&region_) -
      reinterpret_cast<char*>(&build_type_)) + sizeof(region_));
  clear_has_provider();
}

Application::~Application() {
  // @@protoc_insertion_point(destructor:eve_launcher.application.Application)
  SharedDtor();
}

void Application::SharedDtor() {
  version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (has_provider()) {
    clear_provider();
  }
}

void Application::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Application::descriptor() {
  ::protobuf_eve_5flauncher_2fapplication_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_eve_5flauncher_2fapplication_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Application& Application::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_eve_5flauncher_2fapplication_2eproto::scc_info_Application.base);
  return *internal_default_instance();
}


void Application::clear_provider() {
// @@protoc_insertion_point(one_of_clear_start:eve_launcher.application.Application)
  switch (provider_case()) {
    case kNoInstallerProvider: {
      // No need to clear
      break;
    }
    case kInstallerProvider: {
      provider_.installer_provider_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case PROVIDER_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = PROVIDER_NOT_SET;
}


void Application::Clear() {
// @@protoc_insertion_point(message_clear_start:eve_launcher.application.Application)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&build_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&region_) -
      reinterpret_cast<char*>(&build_type_)) + sizeof(region_));
  clear_provider();
  _internal_metadata_.Clear();
}

bool Application::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:eve_launcher.application.Application)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string version = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->version().data(), static_cast<int>(this->version().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "eve_launcher.application.Application.version"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .eve_launcher.application.Application.BuildType build_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_build_type(static_cast< ::eve_launcher::application::Application_BuildType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .eve_launcher.application.Application.Region region = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_region(static_cast< ::eve_launcher::application::Application_Region >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool no_installer_provider = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          clear_provider();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &provider_.no_installer_provider_)));
          set_has_no_installer_provider();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string installer_provider = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_installer_provider()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->installer_provider().data(), static_cast<int>(this->installer_provider().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "eve_launcher.application.Application.installer_provider"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:eve_launcher.application.Application)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:eve_launcher.application.Application)
  return false;
#undef DO_
}

void Application::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:eve_launcher.application.Application)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string version = 1;
  if (this->version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->version().data(), static_cast<int>(this->version().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "eve_launcher.application.Application.version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->version(), output);
  }

  // .eve_launcher.application.Application.BuildType build_type = 2;
  if (this->build_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->build_type(), output);
  }

  // .eve_launcher.application.Application.Region region = 3;
  if (this->region() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->region(), output);
  }

  // bool no_installer_provider = 4;
  if (has_no_installer_provider()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->no_installer_provider(), output);
  }

  // string installer_provider = 5;
  if (has_installer_provider()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->installer_provider().data(), static_cast<int>(this->installer_provider().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "eve_launcher.application.Application.installer_provider");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->installer_provider(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:eve_launcher.application.Application)
}

::google::protobuf::uint8* Application::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:eve_launcher.application.Application)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string version = 1;
  if (this->version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->version().data(), static_cast<int>(this->version().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "eve_launcher.application.Application.version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->version(), target);
  }

  // .eve_launcher.application.Application.BuildType build_type = 2;
  if (this->build_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->build_type(), target);
  }

  // .eve_launcher.application.Application.Region region = 3;
  if (this->region() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->region(), target);
  }

  // bool no_installer_provider = 4;
  if (has_no_installer_provider()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->no_installer_provider(), target);
  }

  // string installer_provider = 5;
  if (has_installer_provider()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->installer_provider().data(), static_cast<int>(this->installer_provider().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "eve_launcher.application.Application.installer_provider");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->installer_provider(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:eve_launcher.application.Application)
  return target;
}

size_t Application::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:eve_launcher.application.Application)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string version = 1;
  if (this->version().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->version());
  }

  // .eve_launcher.application.Application.BuildType build_type = 2;
  if (this->build_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->build_type());
  }

  // .eve_launcher.application.Application.Region region = 3;
  if (this->region() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->region());
  }

  switch (provider_case()) {
    // bool no_installer_provider = 4;
    case kNoInstallerProvider: {
      total_size += 1 + 1;
      break;
    }
    // string installer_provider = 5;
    case kInstallerProvider: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->installer_provider());
      break;
    }
    case PROVIDER_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Application::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:eve_launcher.application.Application)
  GOOGLE_DCHECK_NE(&from, this);
  const Application* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Application>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:eve_launcher.application.Application)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:eve_launcher.application.Application)
    MergeFrom(*source);
  }
}

void Application::MergeFrom(const Application& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:eve_launcher.application.Application)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.version().size() > 0) {

    version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  if (from.build_type() != 0) {
    set_build_type(from.build_type());
  }
  if (from.region() != 0) {
    set_region(from.region());
  }
  switch (from.provider_case()) {
    case kNoInstallerProvider: {
      set_no_installer_provider(from.no_installer_provider());
      break;
    }
    case kInstallerProvider: {
      set_installer_provider(from.installer_provider());
      break;
    }
    case PROVIDER_NOT_SET: {
      break;
    }
  }
}

void Application::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:eve_launcher.application.Application)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Application::CopyFrom(const Application& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:eve_launcher.application.Application)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Application::IsInitialized() const {
  return true;
}

void Application::Swap(Application* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Application::InternalSwap(Application* other) {
  using std::swap;
  version_.Swap(&other->version_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(build_type_, other->build_type_);
  swap(region_, other->region_);
  swap(provider_, other->provider_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Application::GetMetadata() const {
  protobuf_eve_5flauncher_2fapplication_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_eve_5flauncher_2fapplication_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace application
}  // namespace eve_launcher
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::eve_launcher::application::EventMetadata* Arena::CreateMaybeMessage< ::eve_launcher::application::EventMetadata >(Arena* arena) {
  return Arena::CreateInternal< ::eve_launcher::application::EventMetadata >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::eve_launcher::application::Application* Arena::CreateMaybeMessage< ::eve_launcher::application::Application >(Arena* arena) {
  return Arena::CreateInternal< ::eve_launcher::application::Application >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
