win32 {
    7ZIP_BASE=$$PWD/win
    INCLUDEPATH += $$7ZIP_BASE/CPP
    DEFINES += WIN_LONG_PATH _UNICODE
}

unix {
    7ZIP_BASE=$$PWD/unix
    INCLUDEPATH += $$7ZIP_BASE/CPP \
         $$7ZIP_BASE/CPP/myWindows \
        $$7ZIP_BASE/CPP/include_windows

    macx:DEFINES += ENV_MACOSX
    DEFINES += _FILE_OFFSET_BITS=64 _LARGEFILE_SOURCE NDEBUG _REENTRANT ENV_UNIX BREAK_HANDLER UNICODE _UNICODE
}
